#!/usr/bin/env bash
# script display ifromation about domains

print_info()
{
	local domain=$1
	local subdomain=$2
	local record_info
    	record_info=$(dig +noall +answer "${subdomain}.${domain}" | awk 'NR==1{print $5}')
	echo "The subdomain ${subdomain} is a A record and points to ${record_info}"
}

if [ -z "$2" ]; then
	for sub in "www" "lb-01" "web-01" "web-02"; do
		print_info "$1" "$sub"
	done
else
	print_info "$1" "$2"
fi
