#!/usr/bin/env bash
# script display ifromation about domains
SUBS=("www" "lb-01" "web-01" "web-02")


print_info()
{
	DOMAN="$1"
	SUB_DOMAN="$2"
	echo "The subdomain $SUB_DOMAN is a A record and points to $(dig "$SUB_DOMAN"."$DOMAN" +noall +answer | awk 'NR==1{print $5}')"
}

if [[ -n "$1" && "$2" ]]; then
	print_info "$1" "$2"

else
	for sub in "${SUBS[@]}"; do
		print_info "$1" "$sub"
	done
fi
