#!/usr/bin/env bash
# script that transfers a file from our client to a server

[ "$#" -lt 3 ] && echo 'Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY' && exit 1

FILE="$1"
IP="$2"
USER="$3"
SSH_KEY="$4"

scp -i "$SSH_KEY" -o StrictHostKeyChecking=no "$FILE" "$USER"@"$IP":~
