#!/usr/bin/env bash
# configure nignx when querying at root '/' with a GET request using curl

sudo su << EOF > /dev/null 2>&1
sudo apt update -y
sudo apt install nginx -y
sudo ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.html
sudo service nginx restart
exit
EOF
