#!/usr/bin/env bash
# Configure Nginx server so that /redirect_me is redirecting to another page

#line="# pass PHP scripts to FastCGI server"
#repl="location /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}"
file="/etc/nginx/sites-available/default"

sudo apt update
sudo apt install nginx -y
sudo ufw allow 'Nginx HTTP'

echo "server {
	listen 80 default_server;
	listen [::]:80 default_server;

	root /var/www/html;
	index index.html index.htm index.nginx-debian.html;

	server_name _;

	location / {
		return 200 'Hellow World!';
	}
	location /redirect_me {
		return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
	}
}" | sudo tee "$file" > /dev/null

sudo service nginx restart
