#!/usr/bin/env bash
# Configure Nginx server so that /redirect_me is redirecting to another page

line="# pass PHP scripts to FastCGI server"
repl="location /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}"

sudo su << EOF
apt update
apt install nginx -y
ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.html
sed -i "s@$line@$repl@g" /etc/nginx/sites-available/default
EOF
service nginx restart
