#!/usr/bin/env bash
# custom 404 page that contains the string Ceci n'est pas une page

# installed nginx if it's not installed already
[[ $(dpkg-query -W nginx) ]] > /dev/null 2>&1 && apt update && apt install nginx -y

ufw allow 'Nginx HTTP'

echo 'Hello World!' > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/404.html

echo "server {

	listen 80 default_server;
	listen [::]:80 default_server;

	root /var/www/html;

	# Add index.php to the list if you are using PHP
	index index.html index.htm index.nginx-debian.html;

	server_name _;

	location / {
		# First attempt to serve request as file, then
		# as directory, then fall back to displaying a 404.
		try_files \$uri \$uri/ =404;
	}
	location /redirect_me {
		return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
	}
	error_page 404 /404.html;
        location = /404.html {
		root /var/www/html;
                internal;
        }

}" > /etc/nginx/sites-available/default

rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/

service nginx restart
