#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom header (on web-01 and web-02)

HEADER="add_header X-Served-By $(hostname);"

#install nginx
apt update
apt install nginx -y

# append the header
sed -i "/server {/ a $HEADER" /etc/nginx/sites-enabled/default

# restart nginx
service nginx restart
