#!/usr/bin/env bash
# Bash script that:
# Creates the file /var/run/myscript.pid containing its PID
# Displays 'To infinity and beyond' indefinitely
# Displays 'I hate the kill command' when receiving a SIGTERM signal
# Displays 'Y U no love me?!' when receiving a SIGINT signal
# Deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal

file='/var/run/myscript.pid'

# Creating an associative array
declare -A signals=([TERM]="echo I hate the kill command; pkill -f -9 100-process_and_pid_file; rm $file" [INT]="echo Y U no love me?!" [QUIT]="rm $file")

# create file containing its PID
echo "$$" > $file

for sig in "${!signals[@]}"; do
	trap '${signals[$sig]}' "$sig"
done
while ((1)); do
	echo "To infinity and beyond"
	sleep 2
done
