#!/usr/bin/env bash
# Fix this container so that Nginx is running as the nginx user
chown -R nginx:nginx /etc/nginx
chmod -R u+rw /etc/nginx
sed -i '1s/.*/user nginx;/' /etc/nginx/nginx.conf
pkill apache2
sed -i 's/80/8080/g' /etc/nginx/sites-enabled/default
service nginx restart
