#!/usr/bin/env bash
# Fix this container so that Nginx is running as the nginx user

# Change the ownership of the Nginx process to the nginx user
chown -R nginx:nginx /var/cache/nginx /var/run /var/log/nginx
# sed -i '1s/.*/user nginx;/' /etc/nginx/nginx.conf
sed -i 's/\b80\b/8080/g' /etc/nginx/sites-enabled/default
