#!/usr/bin/env bash
# Fix this container so that Nginx is running as the nginx user
chmod 644 /etc/nginx/nginx.conf
sed -i 's/#user www-data;/user nginx;/g' /etc/nginx/nginx.conf
pkill -9 apache2
sed -i 's/80/8080/g' /etc/nginx/sites-enabled/default
sudo -u nginx service nginx restart
