#!/usr/bin/env bash
# Fix this container so that Nginx is running as the nginx user
chmod 644 /etc/nginx/nginx.conf
sed -i '1s/.*/user nginx;/' /etc/nginx/nginx.conf
pkill apache2
sed -i '/listen 80/a listen *:8080;' /etc/nginx/sites-enabled/default
sudo -u nginx service nginx restart
