#!/usr/bin/env bash
# Fix for task1 short and sweet
chown -R nginx:nginx /etc/nginx
sed -i '1s/.*/user nginx;/' /etc/nginx/nginx.conf
pkill apache2
sed -i 's/\b80\b/8080/g' /etc/nginx/sites-enabled/default
sudo -u nginx service nginx restart
