#!/usr/bin/env bash
# gracefully reload gunicorn without interputing running request
: << _COMMENT_
To update an application without downtime, the master will proceed with a progressive rollout of the update.
It will gracefully shut down some workers ( meaning that it will tell workers to finish processing the request they are working on,
but will not send them new requests, once the worker is done, it is will be shutdown),
and start new ones with the new application code or configuration, then move on to the other old workers until it has renewed the whole pool.
_COMMENT_

kill -HUP "$(ps -C gunicorn fch -o pid | head -n 1)"
